<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="containers" nsURI="https://github.com/rdediosb/AppDesigner"
    nsPrefix="containers">
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="archimate.ecore#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkRelationship" eSuperTypes="archimate.ecore#//AssociationRelationship"/>
</ecore:EPackage>
